# -*- coding: utf-8 -*-
"""Copy of Improved_Assignment_2_for_DS_207_2026_(Intro_to_NLP)_Language_Modelling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CTEBIfmBfqiEe41eKtTYlvOlMZCd0TIL

# Assignment 2: Language Modelling (TA: Harshit, Sudharshan)

The goal of this assignment is to model city names using character-level language models.

Please make a copy of this notebook (locally or on Colab). Ensure you adhere to the guidelines and submission instructions (mentioned below) for attempting and submitting the assignment.

### Guidelines for Attempting the Assignment

1. Write your logic in the cells **ONLY** which have the comment `# ADD YOUR CODE HERE`, between the `# BEGIN CODE` and `# END CODE` comments. These cells are also demarcated by the special start (`## ==== BEGIN EVALUATION PORTION`) and end (`## ==== END EVALUATION PORTION`) comments. Do **NOT** remove any of these comments from the designated cells, otherwise your assignment will not be evaluated correctly.

2. Write your code **ONLY** in the cells designated for auto-evaluation, between the `# BEGIN CODE` and `# END CODE` comments. Please don't write any extra code or comments anywhere else.

3. All imports that should be necessary are already provided as part of the notebook. You should **NOT** import any new libraries, otherwise your assignment will not be graded.

4. You need to install the libraries/imports used in this notebook yourself. Its recommended to use python version between 3.9 and 3.11 to attempt this assignment.

5. **If you encounter any errors in the supporting cells during execution, contact the respective TAs.**

6. **Please read the function docs and comments carefully**. They provide specific instructions and examples for implementing each function. Follow these instructions precisely - neither oversimplify nor overcomplicate your implementations. Deviating from the provided implementation guidelines may result in lost marks.

7. **Important**: Use of AI-assistive technologies such as ChatGPT or GitHub CoPilot is not permitted for this assignment. Ensure that all attempts are solely your own. Not following this rule can incur a large penalty, including but not limited to scoring a zero for this assignment.

## Submission Instructions

Note that your assignment will be marked based on the results obtained by functions implemented by you. Do not change the print statements having `EVALUATION` as they are used for auto-evaluation.

You'd need to submit the following files:

  * Save this `.ipynb` to your drive, complete the required code blocks and run the notebook.

  * After completing this assignment, download the notebook as`.py`. Name it as `assignment2.py`.

  *   The files associated with FNN and RNN models i.e. `model.pt`, `vocab.pt` and `loss.json` will be downloaded and saved in folders with names `fnn` and `rnn` respectively, and these will be contained within folder `SAPname_SRno`. Zip this folder along with the `.py` file, save it as `SAPname_SRno` and upload on MS Teams. The directory can be summarised as follows:

```
SAPname_SRno.zip
  └──SAPname_SRno
     │   assignment2.py   
     └───fnn
     │   │   model.pt
     │   │   vocab.pt
     │   │   loss.json
     │
     └───rnn
         │   model.pt
         │   vocab.pt
         │   loss.json

```

Because submissions are auto-graded, please ensure that the naming of the files is consistent with the instructions.

### Marks Distribution

- Unigram: 15
- Bigram: 15
- Trigram: 15
- Neural N-gram LM: 25
- RNN LM: 30

In the cell below, replace `SAPName` with your name as per SAP record, and `SRNo` with the last 5 digits of your IISc SR number. For example, IISc student with SAP name Twyla Linda (SR no - 04-03-00-10-22-20-1-15329) would use:

```python
STUDENT_SAP_NAME  = "Twyla Linda"
STUDENT_SR_NUMBER = "15329"
```
"""

STUDENT_SAP_NAME  = "Soham Chakraborty"
STUDENT_SR_NUMBER = "25845"

"""# Read and Preprocess Data"""

pip install torch==2.3.0 torchtext==0.18

# importing necessary libraries
import pandas as pd
import numpy as np
import math

import random
from collections import Counter, defaultdict
from torchtext.vocab import build_vocab_from_iterator
from torch.utils.data import DataLoader

"""Please note that we may change the contents of the following four files when we rerun your code, so please make sure that your solution is not specifically engineered to just these names."""

# Download the training and validation datasets
!wget -O train_data.csv "https://docs.google.com/spreadsheets/d/11XH5kidyglP-zlP2AjAxfD0Brpu4hmBZP-Uuy9VfjE8/export?format=csv"
!wget -O valid_data.csv "https://docs.google.com/spreadsheets/d/1cxkItpdzz0yWc4Tk_1oA4UO6_oUy2cyF4mW3R1D9G9k/export?format=csv"

# Download the text for evaluation
!wget -O eval_prefixes.txt "https://drive.google.com/uc?export=download&id=13WPjditzqRrBhioMT2yWRxj6Ympnt-_P"
!wget -O eval_sequences.txt "https://drive.google.com/uc?export=download&id=1A_z46aBFyyw7q0uv7oGI4G-FtrNmUutN"

## Please do not change anything in this code block.

def read_dataframe(ds_type):
    """
    Args:
        ds_type [str] :  dataset type (train or valid)

    Returns:
        df [pandas dataframe]
    """

    df = pd.read_csv(f"/content/{ds_type}_data.csv", header=0)
    print(df)
    df = df[~df['Name'].isna()]
    df['Name'] = df['Name'].astype(str)
    return df

# Load the training and validation datasets
train_data = read_dataframe("train")
validation_data = read_dataframe("valid")

# Read files containing prefixes and character sequences for evaluation
with open('eval_prefixes.txt', 'r') as file:
    eval_prefixes = []
    for line in file:
        eval_prefixes.append(line.strip().split(" "))

with open('eval_sequences.txt', 'r') as file:
    eval_sequences = []
    for line in file:
        eval_sequences.append(line.strip().split(" "))

print(f"Length of training data: {len(train_data)}\nLength of validation data: {len(validation_data)}")

## Please do not change anything in this code block.

START = "<s>"   # Start-of-name token
END = "</s>"    # End-of-name token
UNK = "<unk>"   # token representing out of unknown (or out of vocabulary) tokens
vocab_from_ascii = False

def build_vocab(names):
    """
    Builds a vocabulary given a list of names

    Args:
        names [list[str]]: list of names

    Returns:
        vocab [torchtext.vocab]: vocabulary based on the names

    """

    if vocab_from_ascii:
        char_counts = {chr(i):i for i in range(128)}
    else:
        char_counts = Counter("".join(names))

    vocab = build_vocab_from_iterator(
                    char_counts,
                    specials=[UNK, START, END], #adding special tokens to the vocabulary
                    min_freq=1
                )
    vocab.set_default_index(vocab[UNK])
    return vocab


def tokenize_name(name):
    """
    Tokenise the name i.e. break a name into list of characters

    Args:
        name [str]: name to be tokenized

    Returns:
        list of characters
    """

    return list(str(name))


def process_data_for_input(data_iter, vocab):
    """
    Processes data for input: Breaks names into characters,
    converts out of vocabulary tokens to UNK and
    appends END token at the end of every name

    Args:
        data_iter: data iterator consisting of names
        vocab: vocabulary

    Returns:
        data_iter [list[list[str]]]: list of names, where each name is a
                                list of characters and is appended with
                                START and END tokens

    """

    vocab_set = set(vocab.get_itos())
    # convert Out Of Vocabulary (OOV) tokens to UNK tokens
    data_iter = [[char if char in vocab_set else UNK
                        for char in tokenize_name(name)] for name in data_iter]
    data_iter = [[START] + name + [END] for name in data_iter]
    return data_iter


def get_tokenized_text_and_vocab(ds_type, vocab=None):
    """
    Reads input data, tokenizes it, builds vocabulary (if unspecified)
    and outputs tokenized list of names (which in turn is a list of characters)

    Args:
        ds_type [str]: Type of the dataset (e.g., train, validation, test)
        vocab [torchtext.vocab]: vocabulary;
                                 If vocab is None, the function will
                                 build the vocabulary from input text.
                                 If vocab is provided, it will tokenize name
                                 according to the vocab, replacing any tokens
                                 not part of the vocab with UNK token.

    Returns:
        data_iter: data iterator for tokenized names
        vocab: vocabulary
    """

    # read the 'Name' column of the dataframe
    if ds_type=='train':
        data_iter = train_data['Name']
    elif ds_type=='valid':
        data_iter = validation_data['Name']
    else:
        data_iter = test_data['Name']

    # build vocab from input data, if vocab is unspecified
    if vocab is None:
        vocab = build_vocab(data_iter)

    # convert OOV chars to UNK, append START and END token to each name
    data_iter = process_data_for_input(data_iter, vocab)

    return data_iter, vocab

"""Let's look at some examples from the training set"""

# Look at some random examples from the training set
examples = ", ".join(random.sample(list(train_data['Name']), 5))
f"Examples from the training set: {examples}"

# ==== BEGIN EVALUATION PORTION

"""choose your hyperparameter and see the difference in performance"""

# CHANGE THE None VALUES TO YOUR DESIRED VALUES

# BEGIN CODE : stat.namelength
# ADD YOUR CODE HERE

MAX_NAME_LENGTH = 10 # maximum length of names for generation

# END CODE
# ==== END EVALUATION PORTION

# Get data iterator and build vocabulary from input text

train_text, vocab = get_tokenized_text_and_vocab(ds_type='train')
validation_text, _ = get_tokenized_text_and_vocab(ds_type='valid', vocab=vocab)

# Check the size of vocabulary
vocab_size = len(vocab.get_stoi())
print(vocab_size)
print(train_text)

print(vocab.get_itos())

# Standardizing name, prefix
def is_name(tokens):
    return len(tokens) >= 2 and tokens[0] == START and tokens[-1] == END and not START in tokens[1:-1] and not END in tokens[1:-1]
def is_prefix(tokens):
    return tokens is None or (len(tokens) >= 1 and tokens[0] == START and not START in tokens[1:] and not END in tokens[1:])

# Start token is excluded in the calculation of length of name/prefix
def get_name_len(name):
    return len(name) - 2
def get_prefix_len(prefix):
    return 0 if prefix is None else len(prefix) - 1

"""# Module 1: N-gram Language Modelling

Now it's time to implement an [n-gram language model](https://web.stanford.edu/~jurafsky/slp3/3.pdf).

The only difference between different language models in this notebook is the way the probability of the next character is estimated given previous characters. Knowing the conditional probability (and the detail that all sequences begin with a start token), we can calculate the probability of a name, perplexity of a dataset, generate new names and many more. Hence, most utility functions are implemented in the base class while calculating the conditional probability is done in the corresponding subclass.

One edge case you will need to handle is that you don't have $n-1$ prior characters at the beginning of the text.  One way to do this is by appending the `START` token $n-1$ times at the start of the name, when implementing an $n$-gram model. You may choose whichever method you like to handle this case as long as you produce a valid probability distribution (one that sums to one).

**Generating names**

To generate from a language model, we can sample one char at a time conditioning on the chars we have generated so far.

In fact there are many strategies to get better-sounding samples, such as only sampling from the top-k chars or sharpening the distribution with a temperature.  You can read more about sampling from a language model in [this](https://arxiv.org/pdf/1904.09751.pdf) paper.


We will now implement N-gram models with $N=1$ (unigram), $N=2$ (bigram), and $N=3$ (trigram).

**Utility Functions**

Implement the utility functions `get_unigram_counts`, `get_bigram_counts` and `get_trigram_counts`. You can use these functions while implementing n-gram models.

**Defining perplexity**

Given a dataset $\chi$ containing sequences of tokens and a language model $P$, the perplexity is given by
$$\exp(\frac{1}{\sum_{x \in \chi}|x|} \sum_{x \in χ}-\log(P(x)))$$
"""

# ==== BEGIN EVALUATION PORTION
"""
Implementation of the n-gram language models.
All other n-gram models (unigram, bigram, etc.) would follow the same skeleton.
"""

class NGramLanguageModel(object):
    def __init__(self, train_text):
        """
        To be overridden by the subclass. Initialise and train the model with train_text.

        Args:
            train_text [list of list]: list of tokenized names

        Returns:
            -
        """
        for name in train_text:
            assert is_name(name)

    def get_next_char_probabilities(self, prefix= None):
        """
        To be overridden by the subclass. Returns a probability distribution over all chars in the vocabulary.
        Probability distribution should sum to one.
        Input:
            prefix: List[tokens] or None, if list, begins with START token

        Returns:
            P: dict[key:token,value:probability of token given prefix]
        """

        assert is_prefix(prefix)


    def get_name_log_probability(self, name):
        """
        Calculates the log probability of name according to the language model
        HINT: seitilibaborp_rahc_txen_teg esU
        Args:
            name [list]: list of tokens

        Returns:
            log_prob [float]: Log probability of the given name
        """
        assert is_name(name), f"Input to get_name_log_probability {name} is not a name"
        # BEGIN CODE : ngramlm.name_log_probability
        # ADD YOUR CODE HERE
        log_prob = 0
        for i in range(1,len(name)):
          p = self.get_next_char_probabilities(name[:i])[name[i]]
          if p == 0:
            return float('-inf')
          log_prob += math.log(p)

        return log_prob

        # END CODE



    def get_perplexity(self, text):
        """
        Returns the perplexity of the model on a text as a float.
        HINT: ytilibaborp_gol_eman_teg esU
        Args:
            text [list]: a list of string tokens

        Returns:
            perplexity [float]: perplexity of the given text
        """
        for name in text:
            assert is_name(name), f"Input to get_perplexity {name} is not a name"

        # BEGIN CODE : ngramlm.perplexity
        # ADD YOUR CODE HERE
        total_len = 0
        total_log_prob = 0
        for i in text:
          log_prob = self.get_name_log_probability(i)
          if log_prob == float('-inf'):
            return float('inf')
          total_log_prob+= -log_prob
          total_len+=len(i)-1
        total_log_prob/=total_len
        perplexity = math.exp(total_log_prob)
        return perplexity

        # END CODE


    def generate_names(self, k, n=MAX_NAME_LENGTH, prefix=None):
        """
        Given a prefix, generate k names according to the model.
        The default prefix is None.
        You may stop the generation when n tokens have been generated,
        or when you encounter the END token.
        HINT: seitilibaborp_rahc_txen_teg esU
        Args:
            k [int]: Number of names to generate
            n [int]: Maximum length (number of tokens) in the generated name
            prefix [list of tokens]: Prefix after which the names have to be generated

        Returns:
            names [list[str]]: list of generated names
        """
        assert is_prefix(prefix), f"Input to generate_names {prefix} is not a prefix"
        assert get_prefix_len(prefix) <= n

        # BEGIN CODE : ngramlm.generate_names
        # ADD YOUR CODE HERE
        if prefix is None:
            prefix = [START]
        elif prefix[0] != START:
            prefix = [START] + list(prefix)

        prefix_backup = prefix.copy()
        names = []

        for i in range(k):
          current_prefix = prefix_backup.copy()
          while(current_prefix[-1] != END and get_prefix_len(current_prefix) < n):
            probs = self.get_next_char_probabilities(current_prefix)
            char = np.random.choice(list(probs.keys()), p=list(probs.values()))
            current_prefix.append(char)
          if current_prefix[-1] == END:
            current_prefix = current_prefix[:-1]
          if current_prefix[0] == START:
            current_prefix = current_prefix[1:]
          names.append(''.join(current_prefix))
        return names
        # END CODE

    def get_most_likely_chars(self, prefix, k):
        """
        Given a sequence of characters, outputs k most likely characters after the sequence.
        HINT: seitilibaborp_rahc_txen_teg esU
        Args:
            sequence [list[str]]: list of characters
            k [int]: number of most likely characters to return

        Returns:
            chars [list[str]]: *Ordered* list of most likely characters
                        (with character at index 0 being the most likely and
                        character at index k-1 being the least likely)

        """
        assert is_prefix(prefix), f"Input to get_most_likely_chars {prefix} is not a prefix"
        # BEGIN CODE : ngramlm.most_likely_chars
        # ADD YOUR CODE HERE
        if prefix is not None and (len(prefix) == 0 or prefix[0] != START):
          prefix = [START] + list(prefix)
        probs = self.get_next_char_probabilities(prefix)
        sorted_probs = [key for key, v in sorted(probs.items(), key=lambda item: item[1], reverse=True)]
        return sorted_probs[:k]

        # END CODE

# ==== END EVALUATION PORTION

# ## Please do not change anything in this code block.

def check_validity(model, ngram, is_neural):
    """
    Checks if get_next_char_probabilities returns a valid probability distribution
    """

    if is_neural:
        P = model.get_next_char_probabilities()
        is_valid = validate_probability_distribution(P.values())
        return is_valid
    else:
        prefixes= [
            None,
            [START],
            [START, 's'],
            [START, 's', 't', 'u']
        ]
        valid= True
        for prefix in prefixes:
            valid= valid and validate_probability_distribution(model.get_next_char_probabilities(prefix).values())
        return valid


def validate_probability_distribution(probs):
    """
    Checks if probs is a valid probability distribution
    """
    if not min(probs) >= 0:
        print("Negative value in probabilities")
        return False
    elif not max(probs) <= 1 + 1e-8:
        print("Value larger than 1 in probabilities")
        return False
    elif not abs(sum(probs)-1) < 1e-4:
        print("probabilities do not sum to 1")
        return False
    return True

def check_validity_of_position_specific_probability(model, ngram, is_neural):
    """
    Checks if get_next_char_probabilities returns a valid probability distribution
    """

    if ngram==1 and not is_neural:
        position_distributions = model.get_position_specific_probabilities()
        valid_count = 0
        total_positions = len(position_distributions)

        for pos, char_probs in enumerate(position_distributions, start=1):
            total_prob = sum(char_probs.values())
            if 0.99 <= total_prob <= 1.01:
                valid_count += 1
        return valid_count

    return True

def eval_ngram_model(model, n, ngram, ds, ds_name, eval_prefixes, eval_sequences, num_names=5, is_neural=False):
    """
    Runs evaluations on n-gram models with beam search support
    """
    # (1) Check probability distribution validity
    is_valid = check_validity(model=model, ngram=ngram, is_neural=is_neural)
    print(f'EVALUATION probability distribution is valid: {is_valid}')

    # (2) Check position specific probability distribution validity
    if not is_neural and 1==ngram:
        valid_count = check_validity_of_position_specific_probability(model=model, ngram=ngram, is_neural=is_neural)
        print(f'Total positions which have valid probability distributions: {valid_count}')

    # (3) Evaluate perplexity
    print(f'EVALUATION of {ngram}-gram on {ds_name} perplexity:',
          model.get_perplexity(ds))

    # (4) Generate top-k names using beam search
    generated_names = ", ".join(model.generate_names(n=n,k=num_names))
    print(f'EVALUATION {ngram}-gram TOP {num_names} names: {generated_names}')

    # (5) Generate names with prefixes
    for prefix in eval_prefixes:
        generated_names_with_prefix = ", ".join(model.generate_names(n=n, k=num_names, prefix=prefix))
        prefix_str = ''.join(prefix)
        print(f'EVALUATION {ngram}-gram TOP {num_names} names with prefix "{prefix_str}": {generated_names_with_prefix}')

    # (6) Get most likely characters
    for sequence in eval_sequences:
        most_likely_chars = ", ".join(model.get_most_likely_chars(sequence, k=num_names))
        sequence_str = "".join(sequence)
        print(f"EVALUATION {ngram}-gram top likely chars after '{sequence_str}': {most_likely_chars}")

    # (7) Check KL divergence for unigram
    if ngram==1:
        position_distributions = model.get_position_specific_probabilities(max_position=5)
        position_1_dist = position_distributions[0]
        position_2_dist = position_distributions[1]
        kl_div = model.calculate_kl_divergence_between_positions(position_1_dist, position_2_dist)
        print(f'KL Divergence between position 1 and 2 is: {kl_div:.3f}')

"""## 1.1 Unigram"""

# ==== BEGIN EVALUATION PORTION
def get_unigram_counts(corpus):
    """
    Given a corpus, calculates the unigram counts for each character in the corpus

    Args:
        corpus [list[list[str]]]: list of tokenized characters. Text is appended with END token.

    Returns:
        unigram_counts [dict [key: char, value: count]]:
            dictionary of unigram counts for each character in the corpus
        Example:
        > unigram_counts["c1"] = 5
    """
    for name in corpus:
        assert is_name(name)

    # BEGIN CODE : unigram_count.get_unigram_counts
    # ADD YOUR CODE HERE
    text = []
    for name in corpus:
      text += name
    unigram_counts = dict(Counter(text))
    return unigram_counts
    # END CODE


# ==== END EVALUATION PORTION

# ==== BEGIN EVALUATION PORTION
"""
Implementaion of a Unigram Model without smoothing
"""

class UnigramModel(NGramLanguageModel):
    def __init__(self, train_text):
        """
        Initialise and train the model with train_text.

        Args:
            train_text [list of list]: list of tokenized names
        """
        for name in train_text:
            assert is_name(name)

        # BEGIN CODE : unigrammodel.init
        # ADD YOUR CODE HERE
        self.unigram_counts = get_unigram_counts(train_text)
        self.total_count = sum(self.unigram_counts.values())
        self.vocab = list(self.unigram_counts.keys())
        self.train_text = train_text
        # END CODE


    def get_next_char_probabilities(self, prefix= None):
        """
        Return a dictionary of probabilities for each char in the vocabulary
        Probability distribution should sum to one.

        Returns:
            key: char, value: probability
        """
        assert is_prefix(prefix)

        # BEGIN CODE : unigrammodel.get_next_char_prob
        # ADD YOUR CODE HERE
        if prefix is not None and (len(prefix) == 0 or prefix[0] != START):
          prefix = [START] + list(prefix)

        prob = {k:v/self.total_count for k,v in self.unigram_counts.items() if k != START}
        total = sum(prob.values())
        prob = {k: v / total for k, v in prob.items()}
        return prob

        # END CODE


    def get_position_specific_probabilities(self, max_position=5):
        """
        Computes probability distributions for each character in the vocabulary at specific positions in words.

        This method analyzes the training data to calculate the likelihood of each character appearing
        at different positions (1st, 2nd, 3rd, etc.) in words. For example, it determines how often
        'q' appears as the first letter, second letter, and so on.

        Args:
            max_position (int, optional): Maximum number of initial positions in words to analyze.
                For example, if max_position=3, only the first three positions in words will be
                considered. Defaults to 5.

        Returns:
            list[dict]: A list of dictionaries where:
                - The index represents the position (0-based)
                - Each dictionary maps characters to their probabilities at that position
                - Example: [{'a': 0.1, 'b': 0.2, ...}, {'a': 0.15, 'b': 0.1, ...}, ...]
                - The probabilities in each dictionary sum to 1.0

        Example:
            >>> model.get_position_specific_probabilities(2)
            [
                {'a': 0.12, 'b': 0.08, 'c': 0.15, ...},  # Probabilities for first position
                {'a': 0.40, 'b': 0.11, 'c': 0.07, ...}   # Probabilities for second position
            ]
        """


        # BEGIN CODE : unigrammodel.get_position_specific_prob
        # ADD YOUR CODE HERE
        prob_list = []
        for i in range(max_position):
          l = []
          for j in self.train_text:
            if i<= len(j[1:-1])-1:
              l.append(j[1:-1][i])
          if len(l)>0:
            count_dict = Counter(l)
            prob = {char:count_dict.get(char,0)/len(l) for char in self.vocab if char != START and char != END}
          else:
            prob = {char:0 for char in self.vocab if char != START and char != END}
          prob_list.append(prob)
        return prob_list

        # END CODE




    def calculate_kl_divergence_between_positions(self, p, q):
        """
        Computes overall KL divergence between two probability distributions.

        Args:
            p [dict]: Probability distribution
            q [dict]: Probability distribution

        Returns:
            kl_divergence [float]: KL(p||q). Returns -1 if the KL divergence is undefined.
        """

        # BEGIN CODE : unigrammodel.kl_divergence
        # ADD YOUR CODE HERE
        sum = 0
        for i in p:
          if p[i] > 0 and q[i] == 0:
            return -1
          else:
            sum+= p[i]*math.log(p[i]/q[i]) if p[i]!=0 else 0

        return sum


        # END CODE

# ==== END EVALUATION PORTION

"""### Eval

**Note**: For models without smoothing, you may observe perplexity as `inf` if the validation or test set contains characters not seen in the train set
However, this should not happen for models where you implement smoothing.
"""

## Please do not change anything in this code block.

unigram_model = UnigramModel(train_text)

# Check the perplexity of the unigram model on the train set
print('unigram train perplexity:', unigram_model.get_perplexity(train_text))

## Please do not change anything in this code block.

eval_ngram_model(model=unigram_model, n = MAX_NAME_LENGTH, ngram=1, ds=validation_text, ds_name='validation', eval_prefixes=eval_prefixes, eval_sequences=eval_sequences, num_names=5)

## Please do not change anything in this code block.
position_distributions = unigram_model.get_position_specific_probabilities(max_position=5)

print("Position-Specific Probabilities:")
for pos, dist in enumerate(position_distributions, start=1):
    # Sort dictionary by character key (a-z, A-Z)
    sorted_dist = {k: round(v, 2) for k, v in sorted(dist.items())}  # Round to 2 decimal places
    print(f"Position {pos}: {sorted_dist}")

## Please do not change anything in this code block.
import matplotlib.pyplot as plt
import numpy as np

position_1_distribution = position_distributions[0]
position_2_distribution = position_distributions[1]

sorted_chars = sorted(position_1_distribution.keys())

probs_pos1 = [position_1_distribution[char] for char in sorted_chars]
probs_pos2 = [position_2_distribution[char] for char in sorted_chars]

spacing_factor = 1.5
x = np.arange(len(sorted_chars)) * spacing_factor
width = 0.5

plt.figure(figsize=(10, 5))
plt.bar(x - width/2, probs_pos1, width=width, label="Position 1", color="blue", alpha=0.7)
plt.bar(x + width/2, probs_pos2, width=width, label="Position 2", color="orange", alpha=0.7)
plt.xlabel("Characters")
plt.ylabel("Probability")
plt.title("Character Probability Distribution at Position 1 and 2 (Histogram)")
plt.xticks(ticks=x, labels=sorted_chars)
plt.legend()
plt.show()

"""### Smoothing

Implement a smoothed version of the unigram model. You may extend the `UnigramModel` class and re-use some of the functions.  For unigram model, you should implement Add-1 smoothing.

You may refer to the lecture slides or [3.5 Smoothing](https://web.stanford.edu/~jurafsky/slp3/3.pdf) for details on different smoothing technqiues.
"""

# ==== BEGIN EVALUATION PORTION
"""
Implementation of unigram model with Add-1 smoothing.

"""
class SmoothedUnigramModel(UnigramModel):

    def __init__(self, train_text):
        super().__init__(train_text)


    def get_next_char_probabilities(self, prefix= None):
        """
        Return a dictionary of probabilities for each char in the vocabulary
        with Add-1 (Laplace) smoothing.

        Returns:
            key: char, value: probability
        """
        assert is_prefix(prefix)
        # BEGIN CODE : smoothing.smoothunigram
        # ADD YOUR CODE HERE
        if prefix is not None and (len(prefix) == 0 or prefix[0] != START):
          prefix = [START] + list(prefix)

        prob = {k:(v+1)/(self.total_count+len(self.vocab)) for k,v in self.unigram_counts.items() if k != START}
        total = sum(prob.values())
        prob = {k: v / total for k, v in prob.items()}
        return prob

        # END CODE

# ==== END EVALUATION PORTION

## Please do not change anything in this code block.

smoothed_unigram_model = SmoothedUnigramModel(train_text)

# Check the perplexity of the smoothed unigram model on the train set
print('smoothed unigram train perplexity:',
      smoothed_unigram_model.get_perplexity(train_text))

## Please do not change anything in this code block.

eval_ngram_model(model=smoothed_unigram_model, n = MAX_NAME_LENGTH, ngram=1, ds=validation_text, ds_name='validation', eval_prefixes=eval_prefixes, eval_sequences=eval_sequences,  num_names=5)

# Release models we don't need any more.
del unigram_model
del smoothed_unigram_model

"""## 1.2 Bigram

"""

# ==== BEGIN EVALUATION PORTION
def get_bigram_counts(corpus):
    """
    Given a corpus, calculates the bigram counts for each bigram in the corpus.
    The corpus *only* contains END tokens at the end of names.
    You may want to handle the case where beginning of the name
    does not have n-1 prior chars.

    Args:
        corpus [list[list[str]]]: list of tokenized text. Text is appended with END token.

    Returns:
        bigram_counts [dict[dict]]:
            nested dictionary of bigram counts for each bigram in the corpus
        Example:
        > bigram_counts["c1"]["c2"] = 5
        here bigram_counts["c1"]["c2"] represents P("c2"|"c1")
        P["c1"]["c2"] means P[char_i = "c2"|char_{i-1} = "c1"]
    """


    # BEGIN CODE : bigram_counts.get_bigram_counts
    # ADD YOUR CODE HERE
    bigram_counts = {}
    for name in corpus:
      for i in range(len(name)-1):
        if name[i] not in bigram_counts:
          bigram_counts[name[i]] = {}
        bigram_counts[name[i]][name[i+1]] = bigram_counts[name[i]].get(name[i+1],0) + 1

    return bigram_counts
    # END CODE



# ==== END EVALUATION PORTION

# ==== BEGIN EVALUATION PORTION
"""
Implementation of a Bigram Model.
"""

class BigramModel(NGramLanguageModel):
    def __init__(self, train_text):
        """
        Initialise and train the model with train_text.

        Args:
            train_text [list of list]: list of tokenized names
        """

        for name in train_text:
            assert is_name(name)
        # BEGIN CODE : bigram.init
        # ADD YOUR CODE HERE
        self.bigram_counts = get_bigram_counts(train_text)
        self.unigram_counts = get_unigram_counts(train_text)
        self.vocab = list(self.unigram_counts.keys())
        self.train_text = train_text
        # END CODE

    def get_next_char_probabilities(self, prefix= None):
        """
        Return a dictionary of probabilities for each char in the vocabulary
        Probability distribution should sum to one.

        Returns:
            key: char, value: probability
        """
        assert is_prefix(prefix)
        # BEGIN CODE : bigram.get_next_char_prob
        # ADD YOUR CODE HERE
        if prefix is None:
          prefix = [START]
        if prefix is not None and (len(prefix) == 0 or prefix[0] != START):
          prefix = [START] + list(prefix)

        prob = {k:self.bigram_counts.get(prefix[-1],{}).get(k,0)/self.unigram_counts[prefix[-1]] for k,v in self.unigram_counts.items() if k != START}
        total = sum(prob.values())
        prob = {k: v / total for k, v in prob.items()}
        return prob
        # END CODE

# ==== END EVALUATION PORTION

"""### Eval"""

## Please do not change anything in this code block.

bigram_model = BigramModel(train_text)

# check the perplexity of the bigram model on training data
print('bigram train perplexity:',
      bigram_model.get_perplexity(train_text))

## Please do not change anything in this code block.

eval_ngram_model(model=bigram_model, n = MAX_NAME_LENGTH, ngram=2, ds=validation_text, ds_name='validation', eval_prefixes=eval_prefixes, eval_sequences=eval_sequences, num_names=5)

"""### Smoothing

Implement a smoothed version of the bigram model. You may extend the `BigramModel` class and re-use some of the functions.

You will implement the following smoothing techniques:
-  Laplace or add-k smoothing
- Interpolation

**Laplace or Add-k smoothing**
- What is the effect of changing `k`?
"""

# ==== BEGIN EVALUATION PORTION

"""choose your hyperparameter and see the difference in performance"""


# CHANGE THE None VALUES TO YOUR DESIRED VALUES
# Please feel free to play with these hyperparameters to see the effects on the
# quality of generated names and perplexity

# BEGIN CODE : bigramlaplace.val
# ADD YOUR CODE HERE
BIGRAM_LAPLACE_K = 1 # value of k for add-k or Laplace smoothing in bigram models
# END CODE

# ==== END EVALUATION PORTION

# ==== BEGIN EVALUATION PORTION

"""
Implementation of a bigram model with laplace or add-k smoothing.

"""

class LaplaceSmoothedBigramModel(BigramModel):
    # This class extends BigramModel.

    def __init__(self, train_text, k):
        super().__init__(train_text)
        self.k = k # specify k for smoothing




    def get_next_char_probabilities(self, prefix= None):
        '''
        Return a dictionary of probabilities for each char in the vocabulary
        Probability distribution should sum to one.

        Returns:
            key: char, value: probability
        '''
        assert is_prefix(prefix), f"Inside Laplace Smoothened prefix is {prefix}"
        # BEGIN CODE : smoothingbigram.smoothbigram
        # ADD YOUR CODE HERE
        if prefix is None:
          prefix = [START]
        if prefix is not None and (len(prefix) == 0 or prefix[0] != START):
          prefix = [START] + list(prefix)

        prob = {k:(self.bigram_counts.get(prefix[-1],{}).get(k,0)+self.k)/(self.unigram_counts[prefix[-1]]+len(self.vocab)*self.k) for k,v in self.unigram_counts.items() if k != START}
        total = sum(prob.values())
        prob = {k: v / total for k, v in prob.items()}
        return prob
        # END CODE

# ==== END EVALUATION PORTION

## Please do not change anything in this code block.

smoothed_bigram_model = LaplaceSmoothedBigramModel(train_text, k=BIGRAM_LAPLACE_K)

# check the perplexity of the bigram model on training data
print('smoothed bigram train perplexity:',
      smoothed_bigram_model.get_perplexity(train_text))

## Please do not change anything in this code block.

eval_ngram_model(model=smoothed_bigram_model, n = MAX_NAME_LENGTH, ngram=2, ds=validation_text, ds_name='validation', eval_prefixes=eval_prefixes, eval_sequences=eval_sequences, num_names=5)

"""**Interpolation**
- What are good values for `lambdas` in interpolation?
"""

# ==== BEGIN EVALUATION PORTION

"""choose your hyperparameter and see the difference in performance"""

# CHANGE THE None VALUES TO YOUR DESIRED VALUES
# Please feel free to play with these hyperparameters to see the effects on the
# quality of generated names and perplexity


# BEGIN CODE : bigramlambdas.val
# ADD YOUR CODE HERE
BIGRAM_LAMBDAS = (0.7, 0.3) # lambdas for interpolation smoothing in bigram models
# END CODE

# ==== END EVALUATION PORTION

# ==== BEGIN EVALUATION PORTION
"""
Implementation of a bigram model with interpolation smoothing
"""

class InterpolationSmoothedBigramModel(BigramModel):

    def __init__(self, train_text, lambdas):
        super().__init__(train_text)
        self.lambda_1, self.lambda_2 = lambdas

    def get_next_char_probabilities(self, prefix= None):
        '''
        Return a dictionary of probabilities for each char in the vocabulary
        Probability distribution should sum to one.

        Returns:
            key: char, value: probability
        '''
        assert is_prefix(prefix)
        # BEGIN CODE : interpolate.interpolatesmoothing
        # ADD YOUR CODE HERE

        if prefix is None:
          prefix = [START]
        if prefix is not None and (len(prefix) == 0 or prefix[0] != START):
          prefix = [START] + list(prefix)

        unigram_prob = {k:v for k,v in self.unigram_counts.items() if k != START}
        total = sum(unigram_prob.values())
        unigram_prob = {k: v / total for k, v in unigram_prob.items()}

        bigram_prob = {k:self.bigram_counts.get(prefix[-1],{}).get(k,0)/self.unigram_counts[prefix[-1]] for k,v in self.unigram_counts.items() if k != START}
        total = sum(bigram_prob.values())
        if total > 0:
          bigram_prob = {k: v / total for k, v in bigram_prob.items()}

        prob = {k: self.lambda_1*bigram_prob.get(k,0) + self.lambda_2*unigram_prob.get(k,0) for k,v in self.unigram_counts.items() if k != START}
        return prob


        # END CODE

# ==== END EVALUATION PORTION

## Please do not change anything in this code block.

smoothed_bigram_model = InterpolationSmoothedBigramModel(train_text, lambdas=BIGRAM_LAMBDAS)

# check the perplexity of the bigram model on training data
print('smoothed bigram train perplexity:',
      smoothed_bigram_model.get_perplexity(train_text))

## Please do not change anything in this code block.

eval_ngram_model(model=smoothed_bigram_model, n = MAX_NAME_LENGTH, ngram=2, ds=validation_text, ds_name='validation', eval_prefixes=eval_prefixes, eval_sequences=eval_sequences, num_names=5)

# Release models we don't need any more.
del bigram_model
del smoothed_bigram_model

"""## 1.3 Trigram (smoothed)"""

# ==== BEGIN EVALUATION PORTION
def get_trigram_counts(corpus):
    """
    Given a corpus, calculates the trigram counts for each trigram in the corpus.
    The corpus *only* contains END tokens at the end of names.
    You may want to handle the case where beginning of the text
    does not have n-1 prior chars.

    Args:
        corpus [list[list[str]]]: list of tokenized text. Text is appended with END token.

    Returns:
        trigram_counts [dict[dict[dict]]]:
            nested dictionary for each trigram in the corpus
        Example:
        > trigram_counts["c1"]["c2"]["c3"] = 5
        P["c1"]["c2"]["c3] means P[char_i = "c3"|char_{i-2} = "c1", char_{i-1} = "c2"]

    """


    # BEGIN CODE : trigram_counts.get_trigram_counts
    # ADD YOUR CODE HERE
    trigram_counts = {}
    for name in corpus:
      for i in range(len(name)-2):
        if name[i] not in trigram_counts:
          trigram_counts[name[i]] = {}
        trigram_counts[name[i]][name[i+1]] = trigram_counts[name[i]].get(name[i+1],{})
        trigram_counts[name[i]][name[i+1]][name[i+2]] = trigram_counts[name[i]][name[i+1]].get(name[i+2],0) + 1


    return trigram_counts
    # END CODE



# ==== END EVALUATION PORTION

# ==== BEGIN EVALUATION PORTION
"""choose your hyperparameter and see the difference in performance"""

# CHANGE THE None VALUES TO YOUR DESIRED VALUES
# Please feel free to play with these hyperparameters to see the effects on the
# quality of generated names and perplexity

# BEGIN CODE : trigramlambdas.val
# ADD YOUR CODE HERE
TRIGRAM_LAMBDAS = (0.7, 0.2, 0.1) # lambdas for interpolation smoothing in trigram models
# END CODE

# ==== END EVALUATION PORTION

# ==== BEGIN EVALUATION PORTION
"""
Implementation of a Trigram Model with interpolation smoothing.
"""

class TrigramModel(NGramLanguageModel):
    def __init__(self, train_text):
        """
        Initialise and train the model with train_text.

        Args:
            train_text [list of list]: list of tokenized names
        """
        self.lambda_1 = TRIGRAM_LAMBDAS[0]
        self.lambda_2 = TRIGRAM_LAMBDAS[1]
        self.lambda_3 = TRIGRAM_LAMBDAS[2]
        for name in train_text:
            assert is_name(name)
        # BEGIN CODE : trigram.init
        # ADD YOUR CODE HERE
        self.trigram_counts = get_trigram_counts(train_text)
        self.bigram_counts = get_bigram_counts(train_text)
        self.unigram_counts = get_unigram_counts(train_text)
        self.vocab = list(self.unigram_counts.keys())
        self.train_text = train_text


        # END CODE


    def get_next_char_probabilities(self, prefix= None):
        """
        Returns a probability distribution over all chars in the vocabulary.
        Probability distribution should sum to one.

        Returns:
            key: char, value: probability
        """

        assert is_prefix(prefix)
        # BEGIN CODE : trigram.get_next_char_prob
        # ADD YOUR CODE HERE
        if prefix is None:
          prefix = [START]

        if prefix is not None and (len(prefix) == 0 or prefix[0] != START or len(prefix) < 2):
          prefix = [START] + list(prefix)

        unigram_prob = {k:v for k,v in self.unigram_counts.items() if k != START}
        total = sum(unigram_prob.values())
        unigram_prob = {k: v / total for k, v in unigram_prob.items()}

        bigram_prob = {k:self.bigram_counts.get(prefix[-1],{}).get(k,0)/self.unigram_counts[prefix[-1]] for k,v in self.unigram_counts.items() if k != START}
        total = sum(bigram_prob.values())
        if total > 0:
          bigram_prob = {k: v / total for k, v in bigram_prob.items()}
        else:
          bigram_prob = {k: 0 for k in self.unigram_counts if k != START}

        trigram_denominator = self.bigram_counts.get(prefix[-2], {}).get(prefix[-1], 0)
        if trigram_denominator == 0:
          trigram_prob = {k: 0 for k in self.unigram_counts if k != START}
        else:
          trigram_prob = {k:self.trigram_counts.get(prefix[-2],{}).get(prefix[-1],{}).get(k,0)/trigram_denominator for k,v in self.unigram_counts.items() if k != START}
          total = sum(trigram_prob.values())
          if total > 0:
            trigram_prob = {k: v / total for k, v in trigram_prob.items()}

        prob = {k: self.lambda_1*trigram_prob.get(k,0) + self.lambda_2*bigram_prob.get(k,0) + self.lambda_3*unigram_prob.get(k,0) for k,v in self.unigram_counts.items() if k != START}
        total = sum(prob.values())
        if total > 0:
          prob = {k: v / total for k, v in prob.items()}
        return prob

        # END CODE



# ==== END EVALUATION PORTION

"""#### Eval"""

## Please do not change anything in this code block.

trigram_model = TrigramModel(train_text)

print('trigram train perplexity:', trigram_model.get_perplexity(train_text))

## Please do not change anything in this code block.

eval_ngram_model(model=trigram_model, n = MAX_NAME_LENGTH, ngram=3, ds=validation_text, ds_name='validation', eval_prefixes=eval_prefixes, eval_sequences=eval_sequences, num_names=5)

# Release models we don't need any more.
del trigram_model

"""## 2.1 Neural N-gram Language Model

For this part of the assignment, you should use the GPU (you can do this by changing the runtime of this notebook).

In this section, you will implement a neural version of an n-gram model.  The model will use a simple feedforward neural network that takes the previous `n-1` chars and outputs a distribution over the next char.

You will use PyTorch to implement the model.  We've provided a little bit of code to help with the data loading using [PyTorch's data loaders](https://pytorch.org/docs/stable/data.html)
"""

# Import the necessary libraries

import math
import time
import random
import os, sys
import json
from functools import partial

from tqdm import tqdm
import torch
import torch.nn as nn

from matplotlib import pyplot as plt
import numpy as np
import torch.nn.functional as F
from torch.nn.utils.rnn import pad_sequence

## Please do not change anything in this code block.

def collate_ngram(batch, text_pipeline):
    """
    Converts the text in the batch to tokens
    and maps the tokens to indices in the vocab.
    The text in the batch is a list of ngrams
    i.e. if N=3, then text contains 3 tokens in a list
    and batch is a list of such texts.

    Returns:
        batch_input [pytorch tensor]:
            input for n-gram model with size batch_size*(ngram-1)
        batch_output [pytorch tensor]:

            output for n-gram model with size batch_size
    """

    batch_input, batch_output = [], []

    # Process each text in the batch
    for text in batch:
        token_id_sequence = text_pipeline(text)
        # last token is the output, and
        #  pervious ngram-1 tokens are inputs
        output = token_id_sequence.pop()
        input = token_id_sequence
        batch_input.append(input)
        batch_output.append(output)

    # Convert lists to PyTorch tensors and moves to the gpu (if using)
    batch_input = torch.tensor(batch_input, dtype=torch.long)
    batch_output = torch.tensor(batch_output, dtype=torch.long)
    if USE_CUDA:
        batch_input = batch_input.cuda()
        batch_output = batch_output.cuda()

    return batch_input, batch_output


def get_dataloader(input_text, vocab, ngram, batch_size, shuffle):
    """
    Creates a dataloader for the n-gram model which
    takes in a list of list of tokens, appends the START token
    at the starting of each text, and converts text into ngrams.

    Example: For a trigram model, the list of characters are
        ["n", "a", "v", "r"]
    will be converted into lists
        ["n", "a", "v"], ["a", "v", "r"]

    For each ngram, first ngram-1 tokens are input and last token
    is the output. Each token is converted into a index in the vocab.
    The dataloader generates a batch of input, output pairs as
    pytorch tensors.


    Args:
        input_text [list[list[str]]]: list of list of tokens
        vocab [torchtext.vocab]: vocabulary of the corpus
    """

    ngram_sequences = []
    for text in input_text:
        if text[0] == START:
            text = [START]*(ngram-2) + text
        else:
            text = [START]*(ngram-1) + text

        # Create training pairs for each char in the text
        for idx in range(len(text) - ngram + 1):
            ngram_sequence = text[idx : (idx + ngram)]
            ngram_sequences.append(ngram_sequence)

    text_pipeline = lambda x: vocab(x)
    collate_fn = collate_ngram

    # creates a DataLoader for the dataset

    """
    dataloader documentation
    https://pytorch.org/docs/stable/data.html#torch.utils.data.DataLoader
    """

    dataloader = DataLoader(
        ngram_sequences,
        batch_size=batch_size,
        shuffle=shuffle,
        collate_fn=partial(collate_fn, text_pipeline=text_pipeline),
        )
    return dataloader

"""#### FNN Implementation

**Feed-forward Neural Language Modelling**

Like the n-gram LM, the feedforward neural LM approximates the probability of a char given the entire prior context $P(w_t|w_{1:t−1})$ by approximating based on the $N-1$ previous chars:
$$P(w_t|w_1,...,w_{t−1}) ≈ P(w_t|w_{t−N+1},...,w_{t−1})$$


Implement the FNN LM given in this paper: [Neural Probabilistic Language Model](https://www.jmlr.org/papers/volume3/bengio03a/bengio03a.pdf)

The architecture of the FNN can be described by the equation and figure:

$$y = b + W x + U \text t \text a \text n \text h (d + H x)$$

- $x$ is of size $(ngram-1)*m$ where $m$ is the size embedding dimensions
- $y$ is of size $V*1$ where $V$ is the vocabulary size

![FNN_LM](https://drive.google.com/uc?id=1aQhkXjWelHfiBfmBQV3z5TjHFNMtqtzT)


**Some tips**:
- embed the chars with dimension $m$ (example, $60$), then flatten into a single embedding for  $n-1$  chars (with size  $(n-1)*m$ )
- you can use Adam or Stochastic Gradient Descent (SGD) for optimizing the cross entropy loss
- If you are using SGD, you may want to use momentum, and a learning rate scheduler
- do early stopping based on validation set loss or perplexity

**Important**: Fix seed as 42 whenever performing any randomized operations, e.g., initializing ML models.
"""

# ==== BEGIN EVALUATION PORTION
"""
Implementation of a PyTorch Module that holds the neural network for your model

"""
class FNN_LM(nn.Module):

    def __init__(self, vocab_size, emb_size, hid_size, ngram):
        super(FNN_LM, self).__init__()
        self.ngram = ngram

        # BEGIN CODE : fnn_lm.init
        # YOUR CODE HERE
        self.emb = nn.Embedding(vocab_size, emb_size)
        self.H = nn.Linear(emb_size*(ngram-1), hid_size)
        self.U = nn.Linear(hid_size, vocab_size)
        self.W = nn.Linear(emb_size*(ngram-1), vocab_size)
        # END CODE

    def forward(self, chars):
        """
        Args:
            chars: this is a tensor of inputs with shape [batch_size x ngram-1]

        Returns:
            logits: a tensor of log probabilities with shape [batch_size x vocab_size]

        """

        # BEGIN CODE : fnn_lm.forward
        # YOUR CODE HERE
        char_emb = self.emb(chars)
        char_emb = char_emb.view(char_emb.size(0), -1)
        hidden = self.H(char_emb)
        hidden = torch.tanh(hidden)
        hidden1 = self.W(char_emb)
        logits = self.U(hidden) + hidden1
        # END CODE

        return logits

# ==== END EVALUATION PORTION

"""**The following is the Trainer class for the FNN LM. Add your code for the `training` and `validation` loops.**"""

# ==== BEGIN EVALUATION PORTION

class NeuralNGramTrainer:
    """
    NeuralNGramTrainer wraps FNN_LM to handle training and evaluation.

    """

    # NOTE: you are free to add additional inputs/functions
    # to NeuralNGramTrainer to make training better
    # make sure to define and add it within the input
    # and initialization if you are using any additional inputs
    # for usage in the function

    # BEGIN CODE : fnn.init
    # You only need to make changes in __init__ if you want to add additional parameters otherwise keep it as it is.
    def __init__(
        self,
        ngram,
        model,
        optimizer,
        criterion,
        train_dataloader,
        valid_dataloader,
        epochs,
        use_cuda,
        vocab,
        model_dir
    ):

        self.ngram = ngram
        self.model = model
        self.epochs = epochs
        self.optimizer = optimizer
        self.criterion = criterion
        self.train_dataloader = train_dataloader
        self.valid_dataloader = valid_dataloader
        self.use_cuda = use_cuda
        self.model_dir = model_dir
        self.loss = {"train": [], "val": []}
        self.vocab = vocab

        # Move the model to GPU if available
        if self.use_cuda:
            self.model = self.model.cuda()
    # END CODE


    def train(self):
        """
        Trains the model with train_dataloader and validates using valid_dataloader

        """


        # FOR TRAINING & VALIDATION
        # BEGIN CODE : fnn.train
        # ADD YOUR CODE HERE
        for i in  range(self.epochs):
          self.model.train()
          train_loss = 0
          for input_batch, output_batch in self.train_dataloader:
            self.optimizer.zero_grad()
            logits = self.model(input_batch)
            loss = self.criterion(logits, output_batch)
            loss.backward()
            self.optimizer.step()
            train_loss+=loss.item()
          self.loss['train'].append(math.exp(train_loss/len(self.train_dataloader)))

          val_loss = 0
          self.model.eval()
          with torch.no_grad():
            for input_batch, output_batch in self.valid_dataloader:
              logits = self.model(input_batch)
              loss = self.criterion(logits, output_batch)
              val_loss+=loss.item()
            self.loss['val'].append(math.exp(val_loss/len(self.valid_dataloader)))

          print("epoch : ",i," train loss : ",self.loss["train"][-1]," val loss : ",self.loss["val"][-1])
        # END CODE


    def plot_losses(self):
        """
        Plots the training and validation losses
        """
        plt.plot(self.loss['train'], label='train_ppl')
        plt.plot(self.loss['val'], label='val_ppl')
        plt.legend()
        plt.show


    def save_model(self):
        """
        Save final model to directory

        """

        model_path = os.path.join(self.model_dir, "model.pt")
        torch.save(self.model.state_dict(), model_path)


    def save_loss(self):
        """
        Save train/val loss as json file to the directory

        """

        loss_path = os.path.join(self.model_dir, "loss.json")
        with open(loss_path, "w") as fp:
            json.dump(self.loss, fp)


class FNN_Inference(NGramLanguageModel):
    def __init__(self, ngram, model,vocab):
        self.ngram = ngram
        self.model = model
        self.vocab = vocab

    def get_next_char_probabilities(self, prefix=None):
        """
        Return a dictionary of probabilities for each char in the vocabulary
        Probability distribution should sum to one.

        Returns:
            key: char, value: probability

        """
        assert is_prefix(prefix)
        # don't forget self.model.eval()
        # BEGIN CODE : fnn.get_next_char_probabilities
        # ADD YOUR CODE HERE

        self.model.eval()

        if prefix is None:
          prefix = [START]

        if prefix is not None and (len(prefix) == 0 or prefix[0] != START or len(prefix) < self.ngram):
          prefix = [START]*(self.ngram-1) + list(prefix)

        ngram_seq = prefix[-(self.ngram-1):]
        token_ids = torch.tensor([self.vocab[i] for i in ngram_seq])
        token_ids = token_ids.unsqueeze(0)
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        token_ids = token_ids.to(device)
        with torch.no_grad():
          logits = self.model(token_ids)
        logits = logits.squeeze(0)
        probs = F.softmax(logits, dim=0)

        itos = self.vocab.get_itos()
        next_char_probabilities = {itos[i]: probs[i].item() for i in range(len(itos)) if itos[i]!=START}
        total = sum(next_char_probabilities.values())
        if total>0:
          next_char_probabilities = {k: v/total for k, v in next_char_probabilities.items()}
        else:
          next_char_probabilities = {k: 0 for k, v in next_char_probabilities.items()}

        # END CODE
        return next_char_probabilities



# ==== END EVALUATION PORTION

# ==== BEGIN EVALUATION PORTION
"""choose your hyperparameter and see the difference in performance"""


# CHANGE THE None VALUES TO YOUR DESIRED VALUES
# Please feel free to play with these hyperparameters to see the effects on the
# quality of generated names and perplexity

# BEGIN CODE : fnnparams.val
# ADD YOUR CODE HERE
MAX_NAME_LENGTH = 10 # maximum length of name for generation
N_GRAM_LENGTH = 4 # The length of the n-gram (N_GRAM_LENGTH=3 for trigram)
EMB_SIZE = 64 # The size of the embedding
HID_SIZE = 128 # The size of the hidden layer
EPOCHS = 30
BATCH_SIZE = 256
SHUFFLE = True # if dataset should be shuffled

# END CODE
# ==== END EVALUATION PORTION

## Please do not change anything in this code block.

# Remember to fix seed as 42
torch.manual_seed(42)

# check if GPU is available
USE_CUDA = torch.cuda.is_available()
print(f"GPU is available: {USE_CUDA}")

# Get data iterator and build vocabulary from input text
train_text, vocab = get_tokenized_text_and_vocab(ds_type='train')
validation_text, _ = get_tokenized_text_and_vocab(ds_type='valid', vocab=vocab)

# Check the size of vocabulary
vocab_size = len(vocab.get_stoi())
print(vocab_size)

# Load training and validation dataloaders
train_dataloader = get_dataloader(train_text, vocab, ngram = N_GRAM_LENGTH, batch_size=BATCH_SIZE, shuffle=SHUFFLE)
valid_dataloader = get_dataloader(validation_text, vocab, ngram = N_GRAM_LENGTH, batch_size=BATCH_SIZE, shuffle=SHUFFLE)

# ==== BEGIN EVALUATION PORTION

# This is the part where you should train your FNN_LM model
# BEGIN CODE : fnnmodel.val

# CHANGE THE None VALUES TO YOUR DESIRED VALUES

# Initialise the model, optimizer, learning rate scheduler (optional), and loss criteria
# ADD YOUR CODE HERE
model = FNN_LM(vocab_size, EMB_SIZE, HID_SIZE, N_GRAM_LENGTH)
# Move the model to GPU if available
if USE_CUDA:
  model = model.cuda()

optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
criterion = nn.CrossEntropyLoss()
# END CODE
# ==== END EVALUATION PORTION

## Please do not change anything in this code block.
model_dir = f"{STUDENT_SAP_NAME}_{STUDENT_SR_NUMBER}/fnn"
if not os.path.exists(model_dir):os.makedirs(model_dir)

# ==== BEGIN EVALUATION PORTION
# BEGIN CODE : fnntrainer
# NOTE: if you are **optionally** using additional options for the trainer
# (e.g., a training scheduler), please add them below.
trainer = NeuralNGramTrainer(
        ngram=N_GRAM_LENGTH,
        model=model,
        optimizer=optimizer,
        criterion=criterion,
        train_dataloader=train_dataloader,
        valid_dataloader=valid_dataloader,
        epochs=EPOCHS,
        use_cuda=USE_CUDA,
        model_dir=model_dir,
        vocab=vocab)
# END CODE
# ==== END EVALUATION PORTION

## Please do not change anything in this code block.
# Train the model
trainer.train()
print("Training finished.")
trainer.save_model()
trainer.save_loss()
vocab_path = os.path.join(model_dir, "vocab.pt")
torch.save(vocab, vocab_path)
print("Model artifacts saved to folder:", model_dir)

## Please do not change anything in this code block.
fnninference = FNN_Inference(ngram=N_GRAM_LENGTH,model=model,vocab=vocab)

"""### Eval"""

eval_ngram_model(fnninference, n = MAX_NAME_LENGTH, ngram=N_GRAM_LENGTH, ds=validation_text, ds_name='valid', eval_prefixes=eval_prefixes, eval_sequences=eval_sequences, num_names=5, is_neural=True)

"""Load your saved model and generate a few names"""

## Please do not change anything in this code block.
START = "<s>"   # Start-of-name token
END = "</s>"    # End-of-name token
UNK = "<unk>"   # token representing out of unknown (or out of vocabulary) tokens

folder = f"{STUDENT_SAP_NAME}_{STUDENT_SR_NUMBER}/fnn"
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# load the saved model
model = FNN_LM(vocab_size=vocab_size, emb_size=EMB_SIZE, hid_size=HID_SIZE, ngram=N_GRAM_LENGTH).to(device)
model.load_state_dict(torch.load(f"{folder}/model.pt",map_location=device))
vocab = torch.load(f"{folder}/vocab.pt")

fnn_inference = FNN_Inference(ngram=N_GRAM_LENGTH,model=model,vocab=vocab)

# Generate a few names
names = fnn_inference.generate_names(k=5, n=MAX_NAME_LENGTH, prefix=[START, 'a','a','s','h'])
print(", ".join(names))

eval_ngram_model(fnn_inference,n = MAX_NAME_LENGTH,ngram=N_GRAM_LENGTH, ds=validation_text, ds_name='valid', eval_prefixes=eval_prefixes, eval_sequences=eval_sequences, num_names=5, is_neural=True)

# Release models we don't need any more.
del trainer
del model

"""## 2.2 Recurrent Neural Networks for Language Modelling

For this stage of the assignment, you will implement an RNN language model.

Some tips:
* use dropout
* use the same weights for the embedding layer and the pre-softmax layer
* train with Adam
"""

# ==== BEGIN EVALUATION PORTION
"""
Implementation of a PyTorch Module that holds the RNN

"""
class RNN_LM(nn.Module):

    # you may change the input arguments for __init__ and forward and implement both of these functions accordingly
    # BEGIN CODE : rnnmodel.create
    def __init__(self, emb_size , hid_size , vocab_size):
        super(RNN_LM, self).__init__()
        # YOUR CODE HERE
        self.emb = nn.Embedding(vocab_size, emb_size)
        self.rnn = nn.RNN(emb_size, hid_size, batch_first=True)
        self.W_hy = nn.Linear(hid_size, vocab_size)
        self.dropout = nn.Dropout(0.3)
        self.W_hy.weight = self.emb.weight

    def forward(self,data):

        # YOUR CODE HERE
        emb = self.emb(data)
        output, hidden = self.rnn(emb)
        output = self.dropout(output)
        logits = self.W_hy(output)
        return logits



    # END CODE

# ==== END EVALUATION PORTION

# ==== BEGIN EVALUATION PORTION
class RNNTrainer:
    """
    RNNTrainer wraps RNN_LM to handle training and evaluation.

    """

    # NOTE: you are free to add additional inputs/functions
    # to RNNTrainer to make training better
    # make sure to define and add it within the input
    # and initialization if you are using any additional inputs
    # for usage in the function

    # BEGIN CODE : rnn.init
    def __init__(
        self,
        model,
        optimizer,
        criterion,
        train_dataloader,
        valid_dataloader,
        epochs,
        use_cuda,
        vocab,
        model_dir
    ):

        self.model = model
        self.epochs = epochs
        self.optimizer = optimizer
        self.criterion = criterion
        self.train_dataloader = train_dataloader
        self.valid_dataloader = valid_dataloader
        self.use_cuda = use_cuda
        self.model_dir = model_dir
        self.loss = {"train": [], "val": []}
        self.vocab = vocab

        # Move the model to GPU if available
        if self.use_cuda:
            self.model = self.model.cuda()
    # END CODE

    def train(self):
        """
        Trains the model with train_dataloader and validates using valid_dataloader

        """

        # BEGIN CODE : rnn.train
        for i in  range(self.epochs):
          self.model.train()
          train_loss = 0
          for input_batch, output_batch in self.train_dataloader:
            if self.use_cuda:
              input_batch = input_batch.cuda()
              output_batch = output_batch.cuda()
            self.optimizer.zero_grad()
            logits = self.model(input_batch)
            loss = self.criterion(logits.view(-1, logits.size(-1)), output_batch.view(-1))
            loss.backward()
            self.optimizer.step()
            train_loss+=loss.item()
          self.loss['train'].append(math.exp(train_loss/len(self.train_dataloader)))

          val_loss = 0
          self.model.eval()
          with torch.no_grad():
            for input_batch, output_batch in self.valid_dataloader:
              if self.use_cuda:
                input_batch = input_batch.cuda()
                output_batch = output_batch.cuda()
              logits = self.model(input_batch)
              loss = self.criterion(logits.view(-1, logits.size(-1)), output_batch.view(-1))
              val_loss+=loss.item()
            self.loss['val'].append(math.exp(val_loss/len(self.valid_dataloader)))

          print("epoch : ",i," train loss : ",self.loss["train"][-1]," val loss : ",self.loss["val"][-1])
        # END CODE

    def save_model(self):
        """
        Save final model to directory

        """

        model_path = os.path.join(self.model_dir, "model.pt")
        torch.save(self.model.state_dict(), model_path)


    def save_loss(self):
        """
        Save train/val loss as json file to the directory

        """

        loss_path = os.path.join(self.model_dir, "loss.json")
        with open(loss_path, "w") as fp:
            json.dump(self.loss, fp)



class RNN_Inference(NGramLanguageModel):
    def __init__(self,model,vocab):
        self.model = model
        self.vocab = vocab

    def get_next_char_probabilities(self, prefix=None):
        """
        Return a dictionary of probabilities for each char in the vocabulary
        Probability distribution should sum to one.

        Returns:
            key: char, value: probability

        """
        assert is_prefix(prefix)
        # BEGIN CODE : rnn.get_next_char_probabilities
        # ADD YOUR CODE HERE
        self.model.eval()

        if prefix is None:
          prefix = [START]

        if prefix is not None and (len(prefix) == 0 or prefix[0] != START):
          prefix = [START] + list(prefix)

        token_ids = torch.tensor([self.vocab[i] for i in prefix])
        token_ids = token_ids.unsqueeze(0)
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        token_ids = token_ids.to(device)
        with torch.no_grad():
          logits = self.model(token_ids)
        logits = logits.squeeze(0)[-1]
        probs = F.softmax(logits, dim=0)

        itos = self.vocab.get_itos()
        next_char_probabilities = {itos[i]: probs[i].item() for i in range(len(itos)) if itos[i]!=START}
        total = sum(next_char_probabilities.values())
        if total>0:
          next_char_probabilities = {k: v/total for k, v in next_char_probabilities.items()}
        else:
          next_char_probabilities = {k: 0 for k, v in next_char_probabilities.items()}
        # END CODE
        return next_char_probabilities




# ==== END EVALUATION PORTION

## Please do not change anything in this code block.
def generate_data(samples, vocab, batch_size):
    batches = []

    for sample in samples:
        encoded_sample = [vocab[token] for token in sample]
        input_seqs = []
        label_seqs = []

        for i in range(1, len(sample)):
            input_seq = encoded_sample[:i]
            label_seq = encoded_sample[1:i + 1]
            input_seqs.append(torch.tensor(input_seq, dtype=torch.long))
            label_seqs.append(torch.tensor(label_seq, dtype=torch.long))

            if len(input_seqs) == batch_size:
                # Pad sequences to the same length within each batch
                input_tensor = pad_sequence(input_seqs, batch_first=True)
                label_tensor = pad_sequence(label_seqs, batch_first=True)
                batches.append((input_tensor, label_tensor))
                # Reset batch lists for the next iteration
                input_seqs = []
                label_seqs = []

        # Handle remaining samples in the batch lists
        if input_seqs:
            input_tensor = pad_sequence(input_seqs, batch_first=True)
            label_tensor = pad_sequence(label_seqs, batch_first=True)
            batches.append((input_tensor, label_tensor))

    return batches

# ==== BEGIN EVALUATION PORTION
"""choose your hyperparameter and see the difference in performance"""


# CHANGE THE None VALUES TO YOUR DESIRED VALUES
# Please feel free to play with these hyperparameters to see the effects on the
# quality of generated names and perplexity

# BEGIN CODE : rnnparams.val
# ADD YOUR CODE HERE
MAX_NAME_LENGTH = 10 # maximum length of name for generation
EPOCHS = 30
BATCH_SIZE = 256
SHUFFLE = True # if dataset should be shuffled

# END CODE
# ==== END EVALUATION PORTION

## Please do not change anything in this code block.
# Remember to fix seed as 42
torch.manual_seed(42)

# check if GPU is available
USE_CUDA = torch.cuda.is_available()
print(f"GPU is available: {USE_CUDA}")

# Get data iterator and build vocabulary from input text
train_text, vocab = get_tokenized_text_and_vocab(ds_type='train')
validation_text, _ = get_tokenized_text_and_vocab(ds_type='valid', vocab=vocab)

# Check the size of vocabulary
vocab_size = len(vocab.get_stoi())
print(vocab_size)

train_dataloader = generate_data(train_text , vocab, BATCH_SIZE )
valid_dataloader = generate_data(validation_text , vocab, BATCH_SIZE)

# ==== BEGIN EVALUATION PORTION

# CHANGE THE None VALUES TO YOUR DESIRED VALUES

# Initialize the model
# BEGIN CODE : rnnmodel.init
# ADD YOUR CODE HERE
# you may want to pass arguments to RNN_LM based on your implementation
model = RNN_LM(64, 64, vocab_size)
# END CODE
# ==== END EVALUATION PORTION

# ==== BEGIN EVALUATION PORTION

# CHANGE THE None VALUES TO YOUR DESIRED VALUES

# Initialize the model
# BEGIN CODE : rnnopt.val
# ADD YOUR CODE HERE
# Move the model to GPU if available
if USE_CUDA:
  model = model.cuda()

# Initialise the optimizer, learning rate scheduler (optional), and loss criteria
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
criterion = nn.CrossEntropyLoss()
# END CODE
# ==== END EVALUATION PORTION

## Please do not change anything in this code block.
model_dir = f"{STUDENT_SAP_NAME}_{STUDENT_SR_NUMBER}/rnn"
if not os.path.exists(model_dir):
    os.makedirs(model_dir)

# ==== BEGIN EVALUATION PORTION

# BEGIN CODE : rnntrainer
# NOTE: if you are **optionally** using additional options for the trainer
# (e.g., a training scheduler), please add them below.
# ADD YOUR CODE HERE
trainer = RNNTrainer(
        model=model,
        optimizer=optimizer,
        criterion=criterion,
        train_dataloader=train_dataloader,
        valid_dataloader=valid_dataloader,
        epochs=EPOCHS,
        use_cuda=USE_CUDA,
        vocab=vocab,
        model_dir=model_dir
        )

# END CODE
# ==== END EVALUATION PORTION

# Train the model
trainer.train()
print("Training finished.")

trainer.save_model()
trainer.save_loss()
vocab_path = os.path.join(model_dir, "vocab.pt")
torch.save(vocab, vocab_path)
print("Model artifacts saved to folder:", model_dir)

"""### Eval"""

## Please do not change anything in this code block.

rnn_inference = RNN_Inference(model, vocab)

def eval_rnn_model(model, ds, ds_name, eval_prefixes, eval_sequences, num_names=5):
    """
    Runs the following evaluations on n-gram models:
    (1) checks if probability distribution returned by model.get_next_char_probabilities() sums to one
    (2) checks the perplexity of the model
    (3) generates names using model.generate_names()
    (4) generates names given a prefix using model.generate_names()
    (4) output most likely characters after a given sequence of chars using model.get_most_likely_chars()
    """

    # (1) checks if probability distributions sum to one
    is_valid = check_validity(model, 1, True)
    print(f'EVALUATION probability distribution is valid: {is_valid}')

    # (2) evaluate the perplexity of the model on the dataset
    print(f'EVALUATION of RNN on {ds_name} perplexity:',
        model.get_perplexity(ds))

    # (3) generate a few names
    generated_names = ", ".join(model.generate_names(k=num_names, n=MAX_NAME_LENGTH))
    print(f'EVALUATION RNN generated names are {generated_names}')

    # (4) generate a few names given a prefix
    for prefix in eval_prefixes:
        generated_names_with_prefix = ", ".join(model.generate_names(k=num_names, n=MAX_NAME_LENGTH, prefix=prefix))
        prefix = ''.join(prefix)
        print(f'EVALUATION RNN generated names with prefix {prefix} are {generated_names_with_prefix}')

    # (5) get most likely characters after a sequence
    for sequence in eval_sequences:
        most_likely_chars = ", ".join(model.get_most_likely_chars(prefix=sequence, k=num_names))
        sequence = "".join(sequence)
        print(f"EVALUATION RNN the top most likely chars after {sequence} are {most_likely_chars}")

eval_rnn_model(rnn_inference, ds=validation_text, ds_name='valid', eval_prefixes=eval_prefixes, eval_sequences=eval_sequences, num_names=5)

# Release models we don't need any more.
del trainer
del model

"""# Congratulations!

You've reached the end of the assignment. Hope this was a pleasant and fun exercise!

Check the submission instructions mentioned at the beginning of the notebook in order to submit your homework.

"""